# Generated by Django 4.2.11 on 2024-04-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotix_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="texttoimageai",
            name="payload",
            field=models.JSONField(default={}),
        ),
    ]
