# Generated by Django 4.2.11 on 2024-04-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaotix_main', '0003_texttoimageai_display_img_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttoimageai',
            name='payload',
        ),
    ]
