# Generated by Django 4.2.11 on 2024-04-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textImagemain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="texttoimageai",
            name="display_img_text",
            field=models.TextField(default="a"),
            preserve_default=False,
        ),
    ]
